import {
  Routes,
  LoginPageTexts,
  ApiRoutes,
  HomePage,
  FamilyPage,
  Benefits,
  Discovery,
  Discover,
} from "../interfaces";

export const routes: Routes = {
  login: "/",
  otp: "/otp",
  home: "/home",
  family: "/family",
  benefits: "/benefits",
  discover: "/discover",
  discovery: "/discovery",
  notifications: "/notifications",
  about: "/about",
  help: "/help",
  feedback: "/feedback",
  terms: "/terms",
  category: "/discovery/category",
  eligible: "/discovery/eligible",
  schemes: "/discovery/schemes",
  allSchemes: "/schemes/all",
};

export const loginPageTexts: LoginPageTexts = {
  heading: ["आधार संख्या दर्ज करें", "Enter Aadhar Number"],
  validAadharNumber: "219930090365",
  invalidAadharNumber: "2199300903653",
  registrationPortal: ["पंजीकृत नहीं हैं?", "Not Registered on Family ID"],
  button: ["लॉग इन करें", "Login"],
  otpvalue: ["1", "2", "3", "4", "5", "6"],
  chooseLanguage: "Choose your Language",
  clickHerePortalLink: ["Click Here", "यहाँ क्लिक करें"],
  mobileNumber: "8928295005",
  findSchemeButtonText: ["अपने लिए योजनाएं ढूंढें", "Find Schemes for you"],
  loginScenarios: [
    {
      type: "aadhaar",

      credentials: "219930090365",
    },
    {
      type: "mobile",
      credentials: "8928295005",
    },
  ],
};

export const apiRoutes: ApiRoutes = {
  login: {
    method: "POST",
    route: "/auth/login/",
  },
};

export const homePage: HomePage = {
  title: "पासवृक",
  cardHeading: ["फ़ैमिली आईडी", "FAMILY ID"],
  familyIdNumber: ["2199", "3009", "0365"],
  myName: ["गम्मल", "GAMMAL"],
  address: ["मिर्ज़ापुर,CITY NAGAR", "Mirzapur,CITY NAGAR"],
  noFamilyMember: ["#5 सदस्यों", "#5 members"],
  finacialYear: ["वित्तीय वर्ष 2022-23", "FY 2022-23"],
  benifitsFromGovttext: [
    "Availed through Government schemes",
    "सरकारी योजनाओं द्वारा प्राप्त हुए",
  ],
  benifitsAmount: "₹ 225012",
  noOfSchemesText: ["योजनाओं का लाभ उठाया", "Schemes Availed"],
  noOfSchemes: "3",
  homeButtonText: ["Home", "होम"],
  familyButtonText: ["परिवार", "Family"],
  benefitsButtonText: ["लाभ", "Benefits"],
  discoverButtonText: ["खोजें", "Discover"],
  about: ["हमारे बारे में", "About Us"],
  help: ["अक्सर पूछे जाने वाले सवाल", "Help/FAQs"],
  feedback: ["सुझाव", "Feedback"],
  terms: ["नियम एवं शर्तें", "Terms & Conditions"],
  logout: ["लॉग आउट", "Log Out"],
};

export const familyPage: FamilyPage = {
  listOfFamilyMembersHindi: [
    "गम्मल",
    "उमाकांत मौर्या",
    "प्रिया",
    "आशीष मौर्या",
    "मनीष",
  ],
  listOfFamilyMembersEnglish: [
    "GAMMAL",
    "UMAKANT MAURYA",
    "PRIYA",
    "ASHISH MAURYA",
    "MANISH",
  ],
  relationText: ["संबंध", "Relation"],
  genderText: ["लिंग", "Gender"],
  ageText: ["उम्र", "Age"],
  dateOfBirthText: ["जन्मतिथि", "Date of Birth"],
  casteText: ["जाति", "Caste"],
  noteText: [
    "कृपया अपने परिवार की जानकारी को अपडेट रखें।",
    "Please keep your family data updated.",
  ],

  memberData: [
    {
      relation: "SELF",
      gender: "F",
      age: "41",
      dateOfBirth: "1982-01-01",
      cast: "SC",
    },
    {
      relation: "HUSBAND",
      gender: "M",
      age: "40",
      dateOfBirth: "1983-01-01",
      cast: "SC",
    },
    {
      relation: "DAUGHTER",
      gender: "F",
      age: "23",
      dateOfBirth: "2000-01-01",
      cast: "SC",
    },
    {
      relation: "SON",
      gender: "M",
      age: "20",
      dateOfBirth: "2003-01-01",
      cast: "SC",
    },
    {
      relation: "SON",
      gender: "M",
      age: "16",
      dateOfBirth: "2007-01-01",
      cast: "SC",
    },
  ],
};

export const benefits: Benefits = {
  schemesText: ["Schemes", "योजनाएं"],
  transactionsText: ["Transactions", "लेनदेन"],
  totalFamilyBenefitsText: ["Total family benefits", "कुल पारिवारिक लाभ"],
  totalBenefitsAmount: ["₹ 225012", "Rs 225012"],
  schemesCount: ["Schemes : 3", "योजनाएं : 3"],
  servicesText: ["सेवाएँ : 0", "Services : 0"],
  benifitTypeDropdownText: ["लाभ का प्रकार", "Benefit Type"],
  beneficiaryDropdownText: ["लाभार्थी", "Beneficiary"],
  fyDropdownText: ["वित्तीय वर्ष", "FY"],
  benifitTypeDropdownHindi: ["नक़द", "वस्तु के रूप में", "प्रमाणपत्र"],
  benifitTypeDropdownEnglish: ["Cash", "In Kind", "Certificates"],
  beneficiaryDropdownHindi: [
    "गम्मल",
    "उमाकांत मौर्या",
    "प्रिया",
    "आशीष मौर्या",
    "मनीष",
  ],
  beneficiaryDropdownEnglish: [
    "GAMMAL",
    "UMAKANT MAURYA",
    "PRIYA",
    "ASHISH MAURYA",
    "MANISH",
  ],
  fyDropdownHindi: ["2021-22", "2022-23"],
  fyDropdownEnglish: ["2021-22", "2022-23"],
  listOfSchemes: [
    "Kanya Vivaah Sahayata Yojna",
    "Matritva Shishu Evam Balika Madad Yojna",
    "Sant Ravidas Shiksha Sahayta Yojna ",
  ],

  listOfAllTransaction: [
    {
      schemename: "Kanya Vivaah Sahayata Yojna",
      date: "NaN-NaN-NaN",
      amount: "55000",
      name: "मनीष",
    },
    {
      schemename: "Matritva Shishu Evam Balika Madad Yojna",
      date: "NaN-NaN-NaN",
      amount: "20000",
      name: "मनीष",
    },
    {
      schemename: "Matritva Shishu Evam Balika Madad Yojna",
      date: "NaN-NaN-NaN",
      amount: "6000",
      name: "मनीष",
    },
    {
      schemename: "Matritva Shishu Evam Balika Madad Yojna",
      date: "NaN-NaN-NaN",
      amount: "25000",
      name: "मनीष",
    },
    {
      schemename: "Matritva Shishu Evam Balika Madad Yojna",
      date: "NaN-NaN-NaN",
      amount: "27552",
      name: "मनीष",
    },
    {
      schemename: "Matritva Shishu Evam Balika Madad Yojna",
      date: "NaN-NaN-NaN",
      amount: "27234",
      name: "मनीष",
    },
    {
      schemename: "Matritva Shishu Evam Balika Madad Yojna",
      date: "NaN-NaN-NaN",
      amount: "26274",
      name: "मनीष",
    },
    {
      schemename: "Matritva Shishu Evam Balika Madad Yojna",
      date: "NaN-NaN-NaN",
      amount: "27252",
      name: "मनीष",
    },
    {
      schemename: "Sant Ravidas Shiksha Sahayta Yojna",
      date: "NaN-NaN-NaN",
      amount: "5200",
      name: "मनीष",
    },
    {
      schemename: "Sant Ravidas Shiksha Sahayta Yojna",
      date: "NaN-NaN-NaN",
      amount: "5500",
      name: "मनीष",
    },
  ],
};
export const discovery: Discovery = {
  findEligibleSchemesForYouText: [
    "अपने लिए योग्य योजनाएं खोजें",
    "Find eligible schemes for you",
  ],
  enterYourNAmeText: ["अपना नाम दर्ज करें", "Enter your name"],
  selectYourGenderText: ["अपना लिंग चुनें", "Select your gender"],
  enterYourAgeText: ["अपनी आयु दर्ज करें", "Enter your age"],
  areYouDomicileOfUttarpradeshText: [
    "क्या आप उत्तर प्रदेश के निवासी हैं?",
    "Are you domicile of Uttar Pradesh?",
  ],
  genderDropdownHindi: ["पुरुष", "महिला", "अन्य"],
  genderDropdownEng: ["Male", "Female", "Other"],
  domicileStatusHindi: ["हां", "नहीं"],
  domicileStatusEng: ["Yes", "No"],
  pleaseSelectYourCaste: [
    "कृपया अपने वर्ग का चयन करें",
    "Please select your caste",
  ],
  listOfCastsHindi: [
    "सामान्य",
    "अन्य पिछड़ा वर्ग",
    "अनुसूचित जाति",
    "अनुसूचित जनजाति",
    "अन्य",
  ],
  listOfCastsEng: [
    "General",
    "Other Backward Class",
    "Scheduled Caste",
    "Scheduled Tribe",
  ],
  listOfCast: ["General", "OBC", "SC", "ST", "Other"],
  doYouBelongToMinority: [
    "Do you belong to minority?",
    "क्या आप अल्पसंख्यक समुदाय से हैं?",
  ],
  areYouDifferentlyAbled: [
    "क्या आप दिव्यांग हैं?",
    "Are you differently abled?",
  ],
  yesNoOptionHindi: ["हां", "नहीं"],
  yesNoOptionEng: ["Yes", "No"],
  occupationText: ["आपका व्यवसाय क्या है?", "What is your occupation?"],
  annualIncomeText: [
    "आपके परिवार की वार्षिक आय क्या है?",
    "What is your family's annual income?",
  ],
  occupationDropdownEng: [
    "Student",
    "Farmer",
    "Registered Labourer (UPBoCW)",
    "Artisan, Spinners & Weaver",
    "Khadi Artisan",
    "Teacher/Professor/Faculty",
    "Doctor/CA/Lawyer/Engineer",
    "Health Worker",
    "Street Vendor",
    "Unorganised Worker",
    "Self Employed",
    "Retired",
    "Unemployed",
    "Other",
  ],
  occupationDropdownHindi: [
    "छात्र",
    "किसान",
    "पंजीकृत मजदूर (UPBoCW)",
    "कलाकार, धागा बुनने वाले और बुनाईकार",
    "खादी कलाकार",
    "शिक्षक/प्रोफेसर/शिक्षक बनाने वाले",
    "डॉक्टर/सीए/वकील/इंजीनियर",
    "स्वास्थ्य कर्मी",
    "सड़क विक्रेता",
    "असंगठित कामगार",
    "स्वरोजगार",
    "सेवानिवृत्त",
    "बेरोजगार",
    "अन्य",
  ],
  incomeDropdownEng: [
    "0-50,000",
    "50,001-100,000",
    "100,001-200,000",
    "200,001-300,000",
    "300,001-600,000",
    "600,001-800,000",
    "800,001-1,200,000",
    "1,200,001-1,800,000",
    "Other",
  ],
  incomeDropdownHindi: [
    "0-50,000",
    "50,001-100,000",
    "100,001-200,000",
    "200,001-300,000",
    "300,001-600,000",
    "600,001-800,000",
    "800,001-1,200,000",
    "1,200,001-1,800,000",
    "पता नहीं",
  ],
  eligibleSchemeText: [
    "आप नीचे दी गई योजनाओं के लिए पात्र हो सकते हैं...",
    "You might be eligible for the following schemes...",
  ],
  schemesFoundTextOnPopup: [
    "स्कीमें सफलतापूर्वक मिल गईं",
    "Schemes found successfully",
  ],
  selectOneMoreCategoriesToView: [
    "देखने के लिए एक या अधिक श्रेणियां चुनें।",
    "Select one or more categories to view",
  ],
  youMightBeEligibleForTheFollowingSchemesText: [
    "आप नीचे दी गई योजनाओं के लिए पात्र हो सकते हैं...",
    "You might be eligible for the following schemes...",
  ],
  selectSchemeToConfirmYourEligibilityText: [
    "अपनी पात्रता की पुष्टि करने के लिए योजना का चयन करें",
    "Select scheme to confirm your eligibility",
  ],

  benefitText: ["लाभ"],
  documentsText: ["दस्तावेज"],
  youAreNotEligibleText: "क्षमा करें, आप पात्र नहीं हैं",
  NotEligibleText: "आप आवश्यक पात्रता मानकों को पूरा नहीं करते हैं।",
  editResponseText: "उत्तर को दोबारा भरें",
  exploreOtherSchemesText: "अन्य योजनाओं को खोजें",
  congratulationsText: ["बधाई हो!!!", "Congratulations!!!"],
  basedOnInputText: [
    "आपके उत्तरों के आधार पर, आप संभावित रूप से योजना के लिए पात्र हैं। अधिक जानकारी के लिए अपने ग्राम पंचायत कार्यालय पर जा सकते हैं",
    "Based on your inputs, you are potentially eligible for the scheme.",
  ],
  exploreOtherSchemesButtonText: [
    "अन्य योजनाओं को खोजें",
    "Explore other schemes",
  ],
  enterYourMobileNo: [
    "फ़ोन पर जानकारी प्राप्त करने की लिए मोबाइल नंबर दर्ज करें।",
    "Enter your mobile number to receive more information",
  ],
  callMeText: ["मुझे कॉल करो", "Call me"],
};

export const discover: Discover = {
  welcomeText: ["स्वागत!", "Welcome!"],
  discoverSchemesForYouText: [
    "वे योजनाएँ खोजें जिनके लिए आप पात्र हैं।",
    "Discover schemes you are eligible for.",
  ],
  findSchemesForYou: ["अपने लिए योजनाएँ ढूँढें", "Find Schemes for you"],
  reommendedSchemesText: ["शिफारिशी योजनाएँ", "Recommended Schemes"],
  featuredSchemesText: ["विशेष योजनाएँ", "Featured Schemes"],
  schemeCategoryText: ["योजना श्रेणी", "Schemes Category"],
  exploreMoreSchemesText: ["सभी योजनाएँ देखें", "View All Schemes"],
  yourFamilyMayBeEigibleText: [
    "आपका परिवार पात्र हो सकता है",
    "Your family may be eligible for",
  ],
  onGovtPrirityText: ["सरकार की प्राथमिकता पर", "On Government's Priority"],
  schemesText: ["योजनाएँ", "Schemes"],
  forWhomDoYouWantToFindText: [
    "किसके लिए आप खोजना चाहते हैं?",
    "For whom do you want to find for?",
  ],
  withinFamilyButton: ["परिवार के अंदर", "Within Family"],
  othersTextButton: ["अन्य", "Others"],
  letsFindBestSchemesForYoutext: [
    "Let's find the best schemes for you",
    "Let's find the best schemes for you",
  ],
  selectFamilyMember: [
    "Please select Family Member",
    "Please select Family Member",
  ],
};
