export const familyMembers: any = [
  {
    id: 1,
    name: "Narajiya",
    relation: "Self",
    gender: "female",
    age: 36,
    occupation: "Farmer",
    schemesAvailed: 7,
  },
  {
    id: 2,
    name: "Daya",
    relation: "Husband",
    gender: "male",
    age: 36,
    occupation: "Farmer",
    schemesAvailed: 7,
  },
  {
    id: 3,
    name: "Manju",
    relation: "Daughter in law",
    gender: "female",
    age: 36,
    occupation: "Farmer",
    schemesAvailed: 7,
  },
  {
    id: 4,
    name: "Ram Nayan yadav",
    relation: "Son",
    gender: "male",
    age: 36,
    occupation: "Farmer",
    schemesAvailed: 7,
  },
  {
    id: 5,
    name: "Shailendra yadav",
    relation: "Grand son",
    gender: "male",
    age: 36,
    occupation: "Farmer",
    schemesAvailed: 7,
  },
  {
    id: 6,
    name: "Satyam yadav",
    relation: "Grand son",
    gender: "male",
    age: 36,
    occupation: "Farmer",
    schemesAvailed: 7,
  },
  {
    id: 7,
    name: "Anisha",
    relation: "Grand daughter",
    gender: "female",
    age: 36,
    occupation: "Farmer",
    schemesAvailed: 7,
  },
  {
    id: 8,
    name: "Nitya Tiwari",
    relation: "Grand daughter",
    gender: "female",
    age: 36,
    occupation: "Farmer",
    schemesAvailed: 7,
  },
  {
    id: 9,
    name: "Manas Malhotra",
    relation: "Grand son",
    gender: "male",
    age: 36,
    occupation: "Farmer",
    schemesAvailed: 7,
  },
];
