export const faqs: any = [
  {
    id: 1,
    que: "What is Family Passbook?",
    ans: "Family Passbook is a web app for a citizen to track the schemes availed by their family members and find eligible schemes for them.",
    queh: "फैमिली पासबुक क्या है?",
    ansh: "फ़ैमिली पासबुक एक नागरिक के लिए एक वेब ऐप है, जिसके द्वारा नागरिक अपने परिवार के सदस्यों द्वारा प्राप्त योजनाओं को ट्रैक कर सकते हैं तथा उनके लिए योग्य योजनाओं को खोज सकते हैं।",
  },
  {
    id: 2,
    que: "What are the key features of Family Passbook?",
    ans: "Family Passbook has the following features:\n1. Home - For a summary view of family & benefits details\n2. My Family - To view a list of family members registered in a Family ID\n3. Benefit Ledger - To view a ledger of benefits received by the family\n4. Discovery - To find suitable schemes for a citizen.",
    queh: "फैमिली पासबुक की प्रमुख विशेषताएं क्या हैं?",
    ansh: "फैमिली पासबुक में निम्नलिखित विशेषताएं हैं:\n1. होम - परिवार और लाभ के विवरण का एक सारांश दृश्य के लिए।\n2. मेरा परिवार - परिवार आईडी में पंजीकृत परिवार के सदस्यों की एक सूची दृश्य के लिए।\n3. लाभ खाता - परिवार को प्राप्त लाभ की खाता सूची के लिए।\n4. डिस्कवरी - नागरिकों के लिए उपयुक्त योजना खोजने के लिए।",
  },
  {
    id: 3,
    que: "Who can log in to Family Passbook?",
    ans: "Any citizen who is registered in Family ID or Ration Card can log in to Family Passbook.",
    queh: "फैमिली पासबुक में कौन लॉगिन कर सकता है?",
    ansh: "कोई भी नागरिक जो फैमिली आईडी या राशन कार्ड में पंजीकृत है, वह फैमिली पासबुक में लॉगिन कर सकता है।",
  },
  {
    id: 4,
    que: "How can I log in to Family Passbook?",
    ans: "You can log in either through Aadhaar Number or Mobile Number registered in Family ID.\nAadhaar/Mobile number will be authenticated through OTP.",
    queh: "मैं फैमिली पासबुक में कैसे लॉगिन कर सकता हूं?",
    ansh: "आप फैमिली आईडी में पंजीकृत आधार नंबर या मोबाइल नंबर के माध्यम से लॉगिन कर सकते हैं।\nआधार/मोबाइल नंबर को ओटीपी के माध्यम से प्रमाणित किया जाएगा।",
  },
  {
    id: 5,
    que: "In what languages is Family Passbook available?",
    ans: "Family Passbook is available in two languages, English & Hindi.",
    queh: "फैमिली पासबुक किन भाषाओं में उपलब्ध है?",
    ansh: "फैमिली पासबुक दो भाषाओं, अंग्रेजी और हिंदी, में उपलब्ध है।",
  },
  {
    id: 6,
    que: "Why are all family members not visible in Family Passbook?",
    ans: "Only members registered in Family ID or Ration Card are visible in the Family Passbook.",
    queh: "फैमिली पासबुक में परिवार के सभी सदस्य क्यों नहीं दिख रहें हैं?",
    ansh: "फैमिली पासबुक में केवल फैमिली आईडी या राशन कार्ड में पंजीकृत सदस्य दिखते हैं।",
  },
  {
    id: 7,
    que: "Why benefits from all schemes are not available on Benefit Ledger?",
    ans: "Currently, 50 schemes have been integrated with Family ID & Passbook so details of only these schemes are available. Rest of the schemes will be added soon.",
    queh: "लाभ खाता पर सभी योजनाओं का लाभ क्यों नहीं दिख रहीं हैं?",
    ansh: "वर्तमान में, 50 योजनाओं को फैमिली आईडी और पासबुक के साथ जोड़ा गया है, इसलिए केवल इन योजनाओं का विवरण उपलब्ध है। शेष योजनाएं जल्द ही जोड़ी जाएंगी।",
  },
  {
    id: 8,
    que: "Can I find probable schemes for me if I don't have Family ID/Ration Card?",
    ans: "Yes, 'Find Schemes for you' can be used without logging into Family Passbook.",
    queh: "अगर मेरे पास परिवार पहचान पत्र/राशन कार्ड नहीं है तो क्या मैं अपने लिए संभावित योजनाएं ढूंढ सकता हूं?",
    ansh: "हां, 'आपके लिए योजनाएं ढूंढें' का उपयोग फैमिली पासबुक में लॉगिन किए बिना किया जा सकता है।",
  },
  {
    id: 9,
    que: "How can I check for my eligibility and find probable schemes for me?",
    ans: "Passbook has a three-step process for citizens to find probable schemes:\nStep 1 - Citizen enters his/her attributes such as demographic, income, social details, etc.\nStep 2 - Family Passbook finds the relevant schemes.\nStep 3 - Citizen can select a scheme and confirm their eligibility by answering scheme-specific questions.",
    queh: "मैं अपनी पात्रता की जांच कैसे कर सकता हूं और अपने लिए संभावित योजनाएं कैसे ढूंढ सकता हूं?",
    ansh: "नागरिकों के लिए संभावित योजनाओं को खोजने के लिए पासबुक में तीन चरणों वाली प्रक्रिया है:\nचरण 1 - नागरिक अपनी विशेषताओं जैसे जनसांख्यिकीय, आय, सामाजिक विवरण आदि दर्ज करता है।\nचरण 2 - फैमिली पासबुक से संबंधित योजनाओं का पता चलता है।\nचरण 3 - नागरिक एक योजना का चयन कर सकते हैं और योजना विशिष्ट प्रश्नों का उत्तर देकर अपनी पात्रता की पुष्टि कर सकते हैं।",
  },
  {
    id: 10,
    que: "Why am I not able to see all schemes on Discovery?",
    ans: "Currently, around 50 schemes have been integrated with Family ID & Family Passbook. Many schemes will be added soon.",
    queh: "मैं डिस्कवरी पर सभी योजनाएं क्यों नहीं देख पा रहा हूं?",
    ansh: "वर्तमान में, 50 योजनाओं को फैमिली आईडी और पासबुक के साथ जोड़ा गया है, इसलिए केवल इन योजनाओं का विवरण उपलब्ध है। शेष योजनाएं जल्द ही जोड़ी जाएंगी।",
  },
  {
    id: 11,
    que: "I am getting wrong/irrelevant suggestions under Discovery. What should I do?",
    ans: "If you are getting wrong/irrelevant suggestions, please leave your suggestion in the feedback section for the same.",
    queh: "मुझे डिस्कवरी के तहत गलत सुझाव मिल रहे हैं। मुझे क्या करना चाहिए?",
    ansh: "यदि आपको गलत/अप्रासंगिक सुझाव मिल रहा है, तो आप अपना सुझाव फीडबैक सेक्शन में दे सकते हैं।",
  },
  {
    id: 12,
    que: "I am not getting any scheme despite entering my attributes. What should I do?",
    ans: "If you are not getting a scheme after entering your attributes, this means you might not be eligible for the schemes that have been integrated with Family Passbook. You may leave your suggestion in the feedback section for the same.",
    queh: "अपनी विशेषताएँ दर्ज करने के बावजूद मुझे कोई योजना नहीं मिल रही है। मुझे क्या करना चाहिए?",
    ansh: "यदि आपको अपनी विशेषताएँ दर्ज करने के बाद भी योजना नहीं मिल रही है, तो इसका मतलब है कि आप उन योजनाओं के लिए पात्र नहीं हो सकते हैं जिन्हें फैमिली पासबुक के साथ जोड़ा गया है। आप अपना सुझाव फीडबैक सेक्शन में दे सकते हैं।",
  },
];
